### ISSUE TITLE
Release of the test set

### ISSUE THREAD

**Issue by yangchris11** [tmandel/fish-detrac#1]
Amazing works!

I was wondering if the test set is also ready and available for download?

Thanks!

**Comment by tmandel** [comment]
Hi there!

We have the test set ready, but we are concerned about people potentially _training_ on the test set. So we are waiting to publicly release the test set until there is a researcher who has a method that generates good results on the train set, that they wish to try on the test set (for the purposes of writing a paper, etc.).  If that is you, please email tmandel@hawaii.edu with your training results and a short description of your method, and I will work with you on getting you the test set.

Thanks!

**Comment by yangchris11** [comment]
Thank you for your replies! I'll close the issue.
